products:
  restart: always
  build: ./api/api.products/.
  ports:
    - "3000:3000"
  container_name: products
  environment:
    PORT: 3000
    RMQ_HOST: 172.17.0.1
    DEBUG: "true"

sales:
  restart: always
  build: ./api/api.sales/.
  ports:
    - "3001:3001"
  container_name: sales
  environment:
    PORT: 3001
    RMQ_HOST: 172.17.0.1
    DEBUG: "true"

rmq:
  image: "rabbitmq:management"
  container_name: rmq
  hostname: "rmq"
  ports:
    - '15672:15672'
    - '5672:5672'